#pragma once
// 语音识别结果上屏时不依赖 Win32 的判定：走哪条提交路线、目标是否还在前台、TSF 被拒后能不能退回 SendInput、焦点变了要不要取消，以及 ctrl_v 写剪贴板时附带的排除标记。对应 macOS 的 VoiceTextCommit.h 和 VoiceDeactivation.h：识别出的文字只能写进开始录音时的那个应用，绝不写进别的窗口。

#include <cstdint>
#include <string_view>

namespace msime::windows {
enum class VoiceCommitRoute { Tsf, SendInput, CtrlV };

// voice_input.commit_mode 的取值，未知值按 tsf 处理，与 macOS MSIMEVoiceCommitMode 一致。
constexpr VoiceCommitRoute voice_commit_route(std::string_view mode) {
  if (mode == "sendinput")
    return VoiceCommitRoute::SendInput;
  if (mode == "ctrl_v")
    return VoiceCommitRoute::CtrlV;
  return VoiceCommitRoute::Tsf;
}

// SendInput 和 Ctrl+V 只会落到前台窗口，所以投递前前台必须仍是录音的目标：前台进程是焦点租约所属的 TSF 客户端进程（PipeTicket 的 client_pid，已在管道握手时核对过），或者前台窗口仍是开始录音时那一个（`start_window_foreground`）。后一条照顾 TSF 客户端和前台窗口不在同一个进程的应用：UWP 应用的前台窗口属于 ApplicationFrameHost，传统控制台窗口报告的是控制台程序而 TSF 跑在 conhost 里，只比进程会把这些应用里的语音整段丢掉。没有前台窗口或前台是 Server 自己时一律不投递。对应 macOS MSIMEVoiceCommitRoute::current()。
constexpr bool voice_target_in_foreground(uint32_t target, uint32_t foreground,
                                          uint32_t self,
                                          bool start_window_foreground) {
  if (foreground == 0 || foreground == self)
    return false;
  return start_window_foreground || foreground == target;
}

// TSF 路线没送达时是否退回 SendInput。focus_rejected 表示焦点租约已经失效（焦点去了别的输入框或别的窗口），这时文字一律丢弃；只有事务锁忙或管道写失败、而前台仍是录音时那个进程时才退回，避免整段识别结果打进无关窗口。
constexpr bool voice_tsf_refusal_falls_back(bool focus_rejected,
                                            bool target_in_foreground) {
  return !focus_rejected && target_in_foreground;
}

// 原生语音在录音或识别、润色期间焦点租约失效就取消，不做「停止后转写」，和 macOS MSIMEDeactivateVoice 一样：失焦绝不提交语音。面板的审阅录音由 VoiceControllerDispatch 自己按租约收回，不在这里处理。
constexpr bool voice_focus_loss_cancels(bool native, bool in_progress,
                                        bool lease_current) {
  return native && in_progress && !lease_current;
}

// ctrl_v 写剪贴板时一并放入的注册格式，值都是 DWORD 0。ExcludeClipboardContentFromMonitorProcessing 让剪贴板监视程序（包括水杉自己的剪贴板历史）跳过这次内容，另外两个让 Win+V 历史和云剪贴板不保留它，对应 macOS 写入的 org.nspasteboard.ConcealedType / AutoGeneratedType。
struct VoiceClipboardMarker {
  std::wstring_view format;
  uint32_t value = 0;
};
inline constexpr VoiceClipboardMarker voice_clipboard_markers[] = {
    {L"ExcludeClipboardContentFromMonitorProcessing", 0},
    {L"CanIncludeInClipboardHistory", 0},
    {L"CanUploadToCloudClipboard", 0},
};
} // namespace msime::windows
